---
name: Check Markdown files correctness

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # Extract links from Markdown texts and check if they are alive
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      - uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 # for v1.10.0
        with:
          args: --base . -a 100..=103,200..=299,429 --verbose --no-progress --cache --max-cache-age 1d --scheme http --scheme https './**/*.md'
          fail: true

  # Spellcheck Markdown files using `retext` and `remark`
  # Uses: a custom dictionary file
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tbroadley/spellchecker-cli-action@v1
        with:
          # No need to use a dictionary file with the disabled spell plugin 
          # dictionaries: '.github/workflows/dictionary.txt'
          files: "'**/*.md'"
          quiet: true
          plugins: "indefinite-article repeated-words syntax-mentions syntax-urls"
